name: Photo Club Briançonnais

media:
  input: images
  output: /images

content:
  - name: accueil
    label: Page d'accueil
    type: file
    path: index.html
    fields:
      - name: title
        label: Titre
        type: string
      - name: content
        label: Contenu
        type: rich-text
        options:
          format: html

  - name: club
    label: Le Club
    type: file
    path: le-club.html
    fields:
      - name: title
        label: Titre
        type: string
      - name: content
        label: Contenu
        type: rich-text
        options:
          format: html

  - name: activites
    label: Activités
    type: file
    path: activites.html
    fields:
      - name: title
        label: Titre
        type: string
      - name: content
        label: Contenu
        type: rich-text
        options:
          format: html

  - name: galerie
