name: Photo Club Briançonnais

media:
  input: images
  output: /images

content:
  - name: pages
    label: Pages
    type: file
    path: .
    fields:
      - name: title
        label: Titre de la page
        type: string
      - name: content
        label: Contenu
        type: rich-text
        options:
          format: html
    files:
      - label: Accueil
        path: index.html
      - label: Le Club
        path: le-club.html
      - label: Activités
        path: activites.html
      - label: Galerie
        path: galerie.html
      - label: Contact
        path: contact.html
